import sqlite3

# Create a mapping between category IDs and their respective names
categories_mapping = {
    1: 'high performing websites_all industries',
    2: 'high performing websites_all industries_Arts and Entertainment',
    3: 'high performing websites_all industries_Animation and Comics',
    4: 'high performing websites_all industries_Arts and Entertainment - Other',
    5: 'high performing websites_all industries_Books and literature',
    6: 'high performing websites_all industries_Humour',
    7: 'high performing websites_all industries_music',
    8: 'high performing websites_all industries_performing Arts',
    9: 'high performing websites_all industries_tv Movies and Streaming',
    10: 'high performing websites_all industries_visual Arts and Design',
    11: 'high performing websites_business and consumer services',
    12: 'high performing websites_business and consumer services_business and consumer services - Other',
    13: 'high performing websites_business and consumer services_business services',
    14: 'high performing websites_business and consumer services_marketing and Advertising',
    15: 'high performing websites_business and consumer services_online Marketing',
    16: 'high performing websites_business and consumer services_publishing and Printing',
    17: 'high performing websites_business and consumer services_real Estate',
    18: 'high performing websites_business and consumer services_relocation and Household moving',
    19: 'high performing websites_business and consumer services_shipping and Logistics',
    20: 'high performing websites_business and consumer services_textiles',
    21: 'high performing websites_community and society_',
    22: 'high performing websites_community and society_community and Society - Other',
    23: 'high performing websites_community and society_deceased',
    24: 'high performing websites_community and society_faith Beliefs',
    25: 'high performing websites_community and society_holidays and Seasonal Events',
    26: 'high performing websites_community and society_LGBTQ',
    27: 'high performing websites_community and society_philanthropy',
    28: 'high performing websites_community and society_romance and relationships',
    29: 'high performing websites_computer electronics and technology_',
    30: 'high performing websites_computer electronics and technology_advertising Networks',
    31: 'high performing websites_computer electronics and technology_computer Hardware',
    32: 'high performing websites_computer electronics and technology_computer Security',
    33: 'high performing websites_computer electronics and technology_computer Electronics and Technology - other',
    34: 'high performing websites_high performing websites_computer electronics and technology_consumer Electronics',
    35: 'high performing websites_high performing websites_computer electronics and technology_email',
    36: 'high performing websites_computer electronics and technology_filesharing and hosting',
    37: 'high performing websites_computer electronics and technology_graphics Multimedia and Web design',
    38: 'high performing websites_computer electronics and technology_programming and Developer Software',
    39: 'high performing websites_computer electronics and technology_search Engines',
    40: 'high performing websites_computer electronics and technology_social Networks and Online Communities',
    41: 'high performing websites_computer electronics and technology_telecommunications',
    42: 'high performing websites_computer electronics and technology_web hosting and Domain names',
    43: 'high performing websites_e-commerce and shopping_',
    44: 'high performing websites_e-commerce and shopping_auctions',
    45: 'high performing websites_e-commerce and shopping_classifieds',
    46: 'high performing websites_e-commerce and shopping_coupons and REBATES',
    47: 'high performing websites_e-commerce and shopping_e-commerce and Shopping - Other',
    48: 'high performing websites_e-commerce and shopping_marketplace',
    49: 'high performing websites_e-commerce and shopping_price comparison',
    50: 'high performing websites_e-commerce and shopping_tickets',
    51: 'high performing websites_finance',
    52: 'high performing websites_finance_accounting and auditing',
    53: 'high performing websites_finance_banking credit and lending',
    54: 'high performing websites_finance_finance other',
    55: 'high performing websites_finance_financial planning and management',
    56: 'high performing websites_finance_insurance',
    57: 'high performing websites_finance_investing',
    58: 'high performing websites_food and drink',
    59: 'high performing websites_food and drink_beverages',
    60: 'high performing websites_food and drink_cooking and recipes',
    61: 'high performing websites_food and drink_food and drink - other',
    62: 'high performing websites_food and drink_groceries',
    63: 'high performing websites_food and drink_restaurants and delivery',
    64: 'high performing websites_food and drink_vegetarian and vegan',
    65: 'high performing websites_gambling',
    66: 'high performing websites_gambling_bingo',
    67: 'high performing websites_gambling_casino',
    68: 'high performing websites_gambling_gambling - other',
    69: 'high performing websites_gambling_lottery',
    70: 'high performing websites_gambling_poker',
    71: 'high performing websites_gambling_sporting bets',
    72: 'high performing websites_games',
    73: 'high performing websites_games_board and card games',
    74: 'high performing websites_games_games - other',
    75: 'high performing websites_games_puzzles and brainteasers',
    76: 'high performing websites_games_roleplaying games',
    77: 'high performing websites_games_video game consoles and accessories',
    78: 'high performing websites_health',
    79: 'high performing websites_health_addictions',
    80: 'high performing websites_health_alternative and natural medicine',
    81: "high performing websites_health_biotechnology and pharmaceuticals",
    82: "high performing websites_health_children's health",
    83: 'high performing websites_health_dentist and dental services',
    84: 'high performing websites_health_geriatric and aging care',
}
